### ISSUE TITLE
Answer start alignment

### ISSUE THREAD

**Issue by Wikidepia** [piEsposito/br-quad-2.0#1]
Hi, I wanna ask about answer_start alignment. Once you translate the context & answers, answer_start should change too. How do you change it to align with translated context & answers?

Thanks

**Comment by piEsposito** [comment]
Hello @Wikidepia , and thank you for your time to give a look upon this dataset. 

So, in a few words, this problem known, we are taking actions to solve it but it is not yet done. There are some already aligned answers but, for the problematic cases, we are moving towards using crowdsourcing for by-hand edition. 

If you have any ideas on how to solve this problem, you are most welcome to share it with us. 

Best regards,
-Pi

**Comment by Wikidepia** [comment]
Ah okay, thanks for the answer
